### ISSUE TITLE
py_init.hpp problem

### ISSUE THREAD

**Issue by alastair-radcliffe** [bempp/bempp#203]
Hi,

I'm getting an error: cannot convert ‘wchar_t*’ to ‘char*’ for argument ‘1’ to ‘void Py_SetPythonHome(char*)’ in py_init.hpp when i build the master branch of bempp as of today (30/1/15) using the g++-4.7 compiler.

Thanks,

Alastair

[ 27%] Building CXX object lib/CMakeFiles/libbempp.dir/common/py_init.cpp.o
In file included from /usr/lib64/python2.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                 from /usr/lib64/python2.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib64/python2.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.hpp:24,
                 from /storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.cpp:22:
/usr/lib64/python2.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
In file included from /storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.hpp:21:0,
                 from /storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.cpp:22:
/storage/maths/masnaj/i/dont/mod/bempp-build/include/bempp/common/config_python.hpp:6:29: warning: deprecated conversion from string constant to ‘wchar_t*’ [-Wwrite-strings]
In file included from /storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.cpp:22:0:
/storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.hpp: In constructor ‘Bempp::PyInit::PyInit()’:
/storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.hpp:38:40: error: cannot convert ‘wchar_t*’ to ‘char*’ for argument ‘1’ to ‘void Py_SetPythonHome(char*)’
/storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.hpp: In member function ‘void* Bempp::PyInit::numpy_init()’:
/storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.hpp:52:24: error: return-statement with no value, in function returning ‘void*’ [-fpermissive]
make[2]: *** [lib/CMakeFiles/libbempp.dir/common/py_init.cpp.o] Error 1
make[1]: *** [lib/CMakeFiles/libbempp.dir/all] Error 2
make: *** [all] Error 2

**Comment by tbetcke** [comment]
Hi,

thanks for noticing this. The problem is between Python 3.4 and Python 2.7.
In 3.4 the input argument of Py_SetPythonHome is a wchar* in 2.7 it is
char*. I did not notice it when only compiling in 3.4. I will fix it over
the weekend. In the meantime you can just change the variable
config_python.hpp to char* and adapt the file py_init.cpp correspondingly.
But I should upload a fix by Monday.

Best wishes

Timo

On 30 January 2015 at 15:33, alastair-radcliffe <notifications@github.com>
wrote:

> Hi,
>
> I'm getting an error: cannot convert ‘wchar_t*’ to ‘char*’ for argument
> ‘1’ to ‘void Py_SetPythonHome(char*)’ in py_init.hpp when i build the
> master branch of bempp as of today (30/1/15) using the g++-4.7 compiler.
>
> Thanks,
>
> Alastair
>
> [ 27%] Building CXX object lib/CMakeFiles/libbempp.dir/common/py_init.cpp.o
> In file included from
> /usr/lib64/python2.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
> from
> /usr/lib64/python2.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
> from
> /usr/lib64/python2.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
> from /storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.hpp:24,
> from /storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.cpp:22:
> /usr/lib64/python2.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2:
> warning: #warning "Using deprecated NumPy API, disable it by " "#defining
> NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
> In file included from
> /storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.hpp:21:0,
> from /storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.cpp:22:
> /storage/maths/masnaj/i/dont/mod/bempp-build/include/bempp/common/config_python.hpp:6:29:
> warning: deprecated conversion from string constant to ‘wchar_t
>
>
> *’ [-Wwrite-strings] In file included from
> /storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.cpp:22:0:
> /storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.hpp: In
> constructor ‘Bempp::PyInit::PyInit()’:
> /storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.hpp:38:40: error:
> cannot convert ‘wchar_t*’ to ‘char*’ for argument ‘1’ to ‘void
> Py_SetPythonHome(char*)’
> /storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.hpp: In member
> function ‘void* Bempp::PyInit::numpy_init()’:
> /storage/maths/masnaj/i/dont/mod/bempp/lib/common/py_init.hpp:52:24:
> error: return-statement with no value, in function returning ‘void
> *’ [-fpermissive] make[2]: ***
> [lib/CMakeFiles/libbempp.dir/common/py_init.cpp.o] Error 1
> make[1]: *** [lib/CMakeFiles/libbempp.dir/all] Error 2
> make: *** [all] Error 2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/203>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by tbetcke** [comment]
Fixed and compiles fine on my computer under Python 2.7
